import { describe, expect, test } from "bun:test";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { bundleServerSource, compileTargets } from "../src/build/bundler";
import { generateBundleContent } from "../src/build/bundle-generator";
import { Registry } from "../src/core/registry";

describe("Bundler compile targets", () => {
  test("includes every supported standalone Bun target", () => {
    expect(compileTargets).toEqual([
      "bun-darwin-x64",
      "bun-darwin-arm64",
      "bun-linux-x64",
      "bun-linux-arm64",
      "bun-linux-x64-musl",
      "bun-linux-arm64-musl",
      "bun-windows-x64",
      "bun-windows-arm64",
    ]);
  });
});

describe("Bundled server source", () => {
  test("inlines local server entry and server imports into server.mjs", async () => {
    const root = mkdtempSync(join(tmpdir(), "server-bundle-test-"));

    try {
      const srcDir = join(root, "src");
      const serverOutDir = join(root, "dist", "server");
      const clientOutDir = join(root, "dist", "client");
      mkdirSync(srcDir, { recursive: true });

      const serverEntryPath = join(srcDir, "server.ts");
      writeFileSync(
        serverEntryPath,
        [
          "const app = {",
          '  fetch() { return new Response("unique-server-entry"); },',
          "  post() {},",
          "  all() {},",
          "  use() {},",
          "  get() {},",
          "};",
          "export default app;",
          "",
        ].join("\n"),
      );
      writeFileSync(
        join(srcDir, "db.ts"),
        "export const db = { answer: 42 };\n",
      );

      const registry = new Registry();
      registry.set("todos/get-todos", {
        endpoint: "todos/get-todos",
        file: join(srcDir, "todos.ts"),
        fnJs: "() => db.answer",
        imports: [
          {
            named: [{ imported: "db", local: "db" }],
            specifier: "./db",
          },
        ],
      });

      const generated = generateBundleContent(
        registry,
        "src/server.ts",
        serverEntryPath,
        serverOutDir,
        clientOutDir,
        3001,
      );
      expect(generated).not.toBeNull();

      const outfile = await bundleServerSource(generated!, serverOutDir, root);
      const bundled = readFileSync(outfile, "utf-8");

      expect(outfile).toBe(join(serverOutDir, "server.mjs"));
      expect(bundled).toContain(
        "// Auto-generated by vite-plugin-server-sugar - do not edit",
      );
      expect(bundled).toContain("unique-server-entry");
      expect(bundled).toContain("answer: 42");
      expect(bundled).not.toContain("../../src/server");
      expect(bundled).not.toContain("../../src/db");
      expect(bundled).not.toMatch(/from\s+["']\.\.\/\.\.\/src\//);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
